.TH NAME 1
.\" NAME vtkWrapPythonInit, SECTION 1
.SH NAME
vtkWrapPythonInit \- vtkWrapPythonInit
.SH SYNOPSIS
.B vtkWrapPythonInit
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR vtkWrapPythonInit
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
