.TH NAME 1
.\" NAME vtkWrapPython, SECTION 1
.SH NAME
vtkWrapPython \- vtkWrapPython
.SH SYNOPSIS
.B vtkWrapPython
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR vtkWrapPython
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
