#ifndef OPENVDB_VERSION_HAS_BEEN_INCLUDED
#define OPENVDB_VERSION_HAS_BEEN_INCLUDED

#include "Platform.h"

#include <cstddef> // size_t
#include <cstdint> // uint32_t

#define OPENVDB_LIBRARY_MAJOR_VERSION_NUMBER 8
#define OPENVDB_LIBRARY_MINOR_VERSION_NUMBER 1
#define OPENVDB_LIBRARY_PATCH_VERSION_NUMBER 0

#ifndef OPENVDB_ABI_VERSION_NUMBER
#define OPENVDB_ABI_VERSION_NUMBER 8
#endif

#define OPENVDB_LIBRARY_VERSION_STRING "8.1.0"

#define OPENVDB_LIBRARY_ABI_VERSION_STRING "8.1.0abi8"

#define OPENVDB_LIBRARY_VERSION_NUMBER 134283264

#if OPENVDB_ABI_VERSION_NUMBER == OPENVDB_LIBRARY_MAJOR_VERSION_NUMBER
    #define OPENVDB_VERSION_NAME v8_1
#else
    #define OPENVDB_VERSION_NAME v8_1abi8
#endif

#ifdef OPENVDB_REQUIRE_VERSION_NAME
#define OPENVDB_USE_VERSION_NAMESPACE
#else
// The empty namespace clause below ensures that OPENVDB_VERSION_NAME
// is recognized as a namespace name.
#define OPENVDB_USE_VERSION_NAMESPACE \
    namespace OPENVDB_VERSION_NAME {} \
    using namespace OPENVDB_VERSION_NAME;
#endif



#endif // OPENVDB_VERSION_HAS_BEEN_INCLUDED
