#!/bin/sh

PACKAGE=vtk

VERSION=${VERSION:-$2}
TARFILE=${TARFILE:-$3}

if [ -z ${VERSION}]; then
VERSION=`dpkg-parsechangelog | sed -n -e 's/^Version: \(.*\)-[^-]*$/\1/p'`
fi

REVISION=`echo $VERSION | sed -e 's/^.*git//g'`


if [ -z ${TARFILE}]; then
TARFILE=${PACKAGE}_${VERSION}.orig.tar.gz
fi

FOLDER=${PACKAGE}-${VERSION}

# as of Sept 1, 2011, tag v5.8.0 points to commit id 2380face149471e2d8872f52c5a5f6b68fa87885
git clone git://vtk.org/VTK.git $FOLDER
cd $FOLDER
git checkout $REVISION
rm -rf .git
cd ..
GZIP="--best --no-name" tar cfz $TARFILE $FOLDER
