../../Common/vtkTemplateAliasMacro.h            usr/include/vtk-5.6
usr/bin/vtkEncodeString                         usr/lib/vtk-5.6
usr/include/vtk-5.6                             usr/include
usr/lib/vtk-5.6/*.cmake
usr/lib/vtk-5.6/CMake
usr/lib/vtk-5.6/hints
usr/lib/vtk-5.6/libCosmo.so                     usr/lib
usr/lib/vtk-5.6/libMapReduceMPI.so              usr/lib
usr/lib/vtk-5.6/libVPIC.so                      usr/lib
usr/lib/vtk-5.6/libvtkalglib.so                 usr/lib
usr/lib/vtk-5.6/libvtkCharts.so                 usr/lib
usr/lib/vtk-5.6/libvtkCommon.so                 usr/lib
usr/lib/vtk-5.6/libvtkDICOMParser.so            usr/lib
usr/lib/vtk-5.6/libvtkexoIIc.so                 usr/lib
usr/lib/vtk-5.6/libvtkFiltering.so              usr/lib
usr/lib/vtk-5.6/libvtkftgl.so                   usr/lib
usr/lib/vtk-5.6/libvtkGenericFiltering.so       usr/lib
usr/lib/vtk-5.6/libvtkGeovis.so                 usr/lib
usr/lib/vtk-5.6/libvtkGraphics.so               usr/lib
usr/lib/vtk-5.6/libvtkHybrid.so                 usr/lib
usr/lib/vtk-5.6/libvtkImaging.so                usr/lib
usr/lib/vtk-5.6/libvtkInfovis.so                usr/lib
usr/lib/vtk-5.6/libvtkIO.so                     usr/lib
usr/lib/vtk-5.6/libvtkmetaio.so                 usr/lib
usr/lib/vtk-5.6/libvtkParallel.so               usr/lib
usr/lib/vtk-5.6/libvtkproj4.so                  usr/lib
usr/lib/vtk-5.6/libvtkRendering.so              usr/lib
usr/lib/vtk-5.6/libvtksqlite.so                 usr/lib
usr/lib/vtk-5.6/libvtksys.so                    usr/lib
usr/lib/vtk-5.6/libvtkverdict.so                usr/lib
usr/lib/vtk-5.6/libvtkViews.so                  usr/lib
usr/lib/vtk-5.6/libvtkVolumeRendering.so        usr/lib
usr/lib/vtk-5.6/libvtkWidgets.so                usr/lib
../../Utilities/DICOMParser/Copyright.txt       usr/share/doc/libvtk5-dev/copyright.DICOMParser
