../../Common/vtkTemplateAliasMacro.h            usr/include/vtk-5.8
usr/bin/vtkEncodeString                         usr/lib/vtk-5.8
usr/bin/vtkWrapHierarchy                        usr/lib/vtk-5.8
usr/include/vtk-5.8                             usr/include
usr/lib/vtk-5.8/*.cmake
usr/lib/vtk-5.8/CMake
usr/lib/vtk-5.8/hints
usr/lib/vtk-5.8/libCosmo.so                     usr/lib
usr/lib/vtk-5.8/libMapReduceMPI.so              usr/lib
usr/lib/vtk-5.8/libVPIC.so                      usr/lib
usr/lib/vtk-5.8/libvtkalglib.so                 usr/lib
usr/lib/vtk-5.8/libvtkhdf5.so                   usr/lib
usr/lib/vtk-5.8/libvtkCharts.so                 usr/lib
usr/lib/vtk-5.8/libvtkCommon.so                 usr/lib
usr/lib/vtk-5.8/libvtkDICOMParser.so            usr/lib
usr/lib/vtk-5.8/libvtkexoIIc.so                 usr/lib
usr/lib/vtk-5.8/libvtkFiltering.so              usr/lib
usr/lib/vtk-5.8/libvtkftgl.so                   usr/lib
usr/lib/vtk-5.8/libvtkGenericFiltering.so       usr/lib
usr/lib/vtk-5.8/libvtkGeovis.so                 usr/lib
usr/lib/vtk-5.8/libvtkGraphics.so               usr/lib
usr/lib/vtk-5.8/libvtkHybrid.so                 usr/lib
usr/lib/vtk-5.8/libvtkImaging.so                usr/lib
usr/lib/vtk-5.8/libvtkInfovis.so                usr/lib
usr/lib/vtk-5.8/libvtkIO.so                     usr/lib
usr/lib/vtk-5.8/libvtkmetaio.so                 usr/lib
usr/lib/vtk-5.8/libvtkParallel.so               usr/lib
usr/lib/vtk-5.8/libvtkproj4.so                  usr/lib
usr/lib/vtk-5.8/libvtkRendering.so              usr/lib
usr/lib/vtk-5.8/libvtksys.so                    usr/lib
usr/lib/vtk-5.8/libvtkverdict.so                usr/lib
usr/lib/vtk-5.8/libvtkViews.so                  usr/lib
usr/lib/vtk-5.8/libvtkVolumeRendering.so        usr/lib
usr/lib/vtk-5.8/libvtkWidgets.so                usr/lib
../../Utilities/DICOMParser/Copyright.txt       usr/share/doc/libvtk5-dev/copyright.DICOMParser
