.TH NAME 1
.\" NAME vtkEncodeString, SECTION 1
.SH NAME
vtkEncodeString \- vtkEncodeString
.SH SYNOPSIS
.B vtkEncodeString
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR vtkEncodeString
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
